dic 17, 2017 11:20:17 AM ioc.dam.m6.persistencia.UtilitatJdbc onError
GRAVE: null
org.postgresql.util.PSQLException: ERROR: relation "establiment" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:294)
	at ioc.dam.m6.persistencia.UtilitatJdbc.executar(UtilitatJdbc.java:98)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.llegirFitxerSQLIExecutarLo(EstructuraAplicacioBD.java:126)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.crearEstructura(EstructuraAplicacioBD.java:98)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.executaOrdre(EstructuraAplicacioBD.java:85)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.main(EstructuraAplicacioBD.java:36)

dic 17, 2017 11:20:17 AM ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD main
GRAVE: null
ioc.dam.m6.persistencia.excepcions.UtilitatJdbcSQLException: ERROR: relation "establiment" already exists
	at ioc.dam.m6.persistencia.UtilitatJdbc.onError(UtilitatJdbc.java:219)
	at ioc.dam.m6.persistencia.UtilitatJdbc.executar(UtilitatJdbc.java:101)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.llegirFitxerSQLIExecutarLo(EstructuraAplicacioBD.java:126)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.crearEstructura(EstructuraAplicacioBD.java:98)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.executaOrdre(EstructuraAplicacioBD.java:85)
	at ioc.dam.m6.eac4.aplicacio.controlsgbd.EstructuraAplicacioBD.main(EstructuraAplicacioBD.java:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "establiment" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:294)
	at ioc.dam.m6.persistencia.UtilitatJdbc.executar(UtilitatJdbc.java:98)
	... 4 more

